language: "en_core_web_md"
pipeline: "pretrained_embeddings_spacy"


policies:
  - name: KerasPolicy
    epochs: 500
    max_history: 3
  - name: MemoizationPolicy
    max_history: 3
  - name: FallbackPolicy
    nlu_threshold: 0.1
    core_threshold: 0.2
    fallback_action_name: 'utter_default'
